-- ────────────────────────────────────────────────────────
-- seed_expanded.sql — Expansión de enfermedades SAG/INIA
-- Agrega datos para todos los cultivos del selector
-- Idempotente: usa ON CONFLICT DO NOTHING
-- ────────────────────────────────────────────────────────

INSERT INTO public.enfermedades_sag (cultivo, nombre, nombre_cientifico, sintomas, causa, urgencia, productos_certificados_sag, alternativa_hogar)
VALUES
-- Papa
('Papa', 'Tizón tardío de la papa', 'Phytophthora infestans', 'Manchas negras-marrones en hojas con bordes acuosos. En tallos aparecen lesiones oscuras. Tubérculos con manchas marrones internas.', 'Hongo oomiceto favorecido por temperaturas 10-20°C y alta humedad. Lluvias frecuentes dispersan esporas.', 'Alta', ARRAY['Metalaxil-M + Mancozeb (2.5 kg/ha)', 'Dimetomorf (1 L/ha)', 'Cimoxanil (0.3 kg/ha)'], 'Eliminar plantas afectadas. No almacenar tubérculos dañados. Mejorar drenaje.'),
('Papa', 'Sarna común', 'Streptomyces scabies', 'Costras marrones y rugosas en la superficie de los tubérculos. Lesiones superficiales que no afectan la pulpa.', 'Bacteria del suelo favorecida por suelos alcalinos (pH > 6.5) y secos. Más común en temporadas cálidas.', 'Baja', ARRAY['No hay control químico directo', 'Mantener pH del suelo entre 5.0-5.5', 'Rotación de cultivos (3+ años)'], 'Mantener humedad constante durante formación de tubérculos. Usar semilla certificada.'),

-- Pepino
('Pepino', 'Mildiú velloso del pepino', 'Pseudoperonospora cubensis', 'Manchas amarillas angulares en hojas, limitadas por nervaduras. En envés aparece moho gris-violáceo. Defoliación rápida.', 'Hongo favorecido por temperaturas 15-25°C, alta humedad (>85%) y rocío matinal. Dispersión por viento.', 'Alta', ARRAY['Fosetil-Al (3 L/ha)', 'Metalaxil-M (1 L/ha)', 'Cobre oxicloruro (3 kg/ha)'], 'Caldo bordelés 10g/L cada 7 días. Espaciar riego. Ventilar invernaderos.'),
('Pepino', 'Oídio del pepino', 'Podosphaera xanthii', 'Polvo blanco en hojas y tallos. Hojas se vuelven amarillas y secas. Frutos pueden quedar expuestos al sol.', 'Hongo favorecido por temperaturas 20-30°C y humedad moderada. Mala circulación de aire.', 'Media', ARRAY['Azufre micronizado (2 kg/ha)', 'Penconazol (0.3 L/ha)', 'Miclonautil (0.5 L/ha)'], 'Azufre en polvo cada 7-10 días. Bicarbonato de sodio 5g/L.'),

-- Pimiento
('Pimiento', 'Mancha bacteriana', 'Xanthomonas campestris', 'Manchas oscuras acuosas en hojas que se vuelven marrones con bordes amarillos. Lesiones elevadas en frutos.', 'Bacteria favorecida por temperaturas 25-30°C y alta humedad. Se propaga por salpicadura de agua y herramientas.', 'Media', ARRAY['Cobre oxicloruro (3 kg/ha)', 'Sulfato de cobre pentahidratado (2 kg/ha)', 'Estreptomicina agrícola (0.5 kg/ha)'], 'Evitar riego por aspersión. Desinfectar herramientas. Rotación de cultivos.'),
('Pimiento', 'Trips', 'Frankliniella occidentalis', 'Raspado y deformación de hojas jóvenes. Manchas plateadas. Frutos deformes con cicatrices. Transmite virus.', 'Insecto favorecido por clima cálido-seco. Se reproduce rápidamente en invernaderos.', 'Media', ARRAY['Spinosad (0.5 L/ha)', 'Abamectina (0.6 L/ha)', 'Beauveria bassiana (2 kg/ha)'], 'Trampas adhesivas azules. Depredadores naturales (Orius insidiosus).'),

-- Zapallo
('Zapallo', 'Oídio del zapallo', 'Erysiphe cichoracearum', 'Polvo blanco en hojas y tallos. Hojas se vuelven amarillas y mueren prematuramente. Frutos pequeños y de baja calidad.', 'Hongo favorecido por temperaturas 20-25°C y humedad moderada. Alta densidad de siembra.', 'Media', ARRAY['Azufre micronizado (2 kg/ha)', 'Triflumizol (0.5 L/ha)', 'Penconazol (0.3 L/ha)'], 'Azufre en polvo cada 10 días. Leche diluida 1:9 cada semana.'),
('Zapallo', 'Pudrición de frutos', 'Fusarium spp.', 'Frutos que se pudren desde la base en contacto con el suelo. Manchas blandas acuosas que avanzan rápidamente.', 'Hongo del suelo favorecido por exceso de humedad y frutos en contacto directo con suelo húmedo.', 'Alta', ARRAY['No hay control químico directo efectivo', 'Benomilo (1 kg/ha) en drench preventivo'], 'Mulch de paja o plástico bajo los frutos. Mejorar drenaje. Separar frutos del suelo.'),

-- Brócoli / Repollo
('Brócoli / Repollo', 'Hernia de las crucíferas', 'Plasmodiophora brassicae', 'Raíces deformadas con agallas o nudos. Plantas se marchitan en días cálidos. Hojas con tonos púrpura-amarillentos.', 'Hongo del suelo que sobrevive muchos años. Favorecido por suelos ácidos (pH < 6.0) y húmedos.', 'Alta', ARRAY['No hay control químico curativo', 'Cal agrícola (2-4 ton/ha) para elevar pH', 'Fluazinam (3 L/ha) en drench'], 'Encalar el suelo a pH 6.5-7.0. Rotación larga (5+ años). Eliminar plantas infectadas.'),
('Brócoli / Repollo', 'Pulgón del repollo', 'Brevicoryne brassicae', 'Colonias de pequeños insectos gris-verdosos cubiertos de cera blanca en hojas y cogollos. Hojas enrolladas y pegajosas.', 'Insecto favorecido por clima templado (15-25°C). Se reproduce rápidamente en primavera y otoño.', 'Media', ARRAY['Imidacloprid (0.5 L/ha)', 'Pirimicarb (0.5 kg/ha)', 'Azadiractina (1 L/ha)'], 'Jabón potásico 20ml/L cada 3 días. Depredadores: chinitas (Coccinellidae).'),

-- Manzana
('Manzana', 'Sarna del manzano', 'Venturia inaequalis', 'Manchas verde-oliva a marrón-negras en hojas y frutos. Hojas se deforman y caen. Frutos con costras agrietadas.', 'Hongo que pasa el invierno en hojas caídas. Favorecido por lluvias en primavera y temperaturas 15-20°C.', 'Alta', ARRAY['Dodina (1.5 L/ha)', 'Captan (3 kg/ha)', 'Trifloxistrobina (0.3 L/ha)'], 'Recoger y eliminar hojas caídas en otoño. Azufre cálcico en invierno. Poda de ventilación.'),
('Manzana', 'Polilla de la manzana', 'Cydia pomonella', 'Gusanos dentro de los frutos. Pequeños agujeros de entrada con excrementos. Frutos caen prematuramente.', 'Insecto que pasa el invierno como larva en la corteza. Activo desde brotación hasta cosecha.', 'Alta', ARRAY['Fenoxicarb (1 L/ha)', 'Clorpirifos (2 L/ha)', 'Bacillus thuringiensis (1.5 kg/ha)'], 'Trampas de feromonas para monitoreo. Bolsas de papel alrededor de frutos. Recolectar frutos caídos.'),

-- Peral
('Peral', 'Fuego bacteriano', 'Erwinia amylovora', 'Brotes y flores se vuelven negros como quemados. Bacterias exudan un líquido lechoso. Ramas se encorvan en forma de cayado.', 'Bacteria muy contagiosa favorecida por temperaturas 20-30°C y humedad. Entra por flores y heridas.', 'Alta', ARRAY['Estreptomicina (0.5 kg/ha)', 'Cobre fijo (3 kg/ha) preventivo', 'No hay cura una vez infectado'], 'PODA drástica 30cm bajo la lesión. Desinfectar tijeras con alcohol. Eliminar plantas hospederas (espino).'),
('Peral', 'Roya del peral', 'Gymnosporangium sabinae', 'Manchas anaranjadas brillantes en hojas en primavera. En verano aparecen pústulas en el envés. Defoliación prematura.', 'Hongo que necesita enebros/juníperos como hospedero alternante. Esporas viajan 2-3 km.', 'Media', ARRAY['Azufre mojable (4 kg/ha)', 'Triadimefon (0.5 L/ha)', 'Mancozeb (3 kg/ha)'], 'Eliminar enebros cercanos. Azufre en polvo desde brotación. Recoger hojas infectadas.'),

-- Cerezo
('Cerezo', 'Monilia del cerezo', 'Monilinia laxa', 'Flores y brotes se marchitan y secan como quemados. Frutos con manchas marrones que se pudren y momifican.', 'Hongo que entra por flores. Favorecido por lluvias en floración y temperaturas 15-20°C.', 'Alta', ARRAY['Ciprodinil + Fludioxonil (1.2 kg/ha)', 'Fenhexamida (1.5 L/ha)', 'Captan (3 kg/ha)'], 'Eliminar frutos momificados en invierno. Poda de ramas secas. No mojar flores en riego.'),
('Cerezo', 'Pulgón negro del cerezo', 'Myzus cerasi', 'Colonias de pulgones negro-oscuro en brotes nuevos y envés de hojas. Hojas se enrollan y deforman. Crecimiento detenido.', 'Insecto favorecido por temperaturas 20-25°C. Hormigas protegen las colonias.', 'Media', ARRAY['Imidacloprid (0.5 L/ha)', 'Pirimicarb (0.5 kg/ha)', 'Aceite mineral parafínico (10 L/ha)'], 'Jabón potásico 20ml/L. Controlar hormigas. Depredadores: chinitas y sírfidos.'),

-- Duraznero
('Duraznero', 'Gomosis del duraznero', 'Botryosphaeria dothidea', 'Exudación de goma (gomosis) en ramas y tronco. Corteza se oscurece y muere. Hojas se marchitan y ramas se secan.', 'Hongo que entra por heridas de poda o heladas. Favorecido por estrés hídrico y exceso de nitrógeno.', 'Media', ARRAY['Cobre oxicloruro (3 kg/ha) en invierno', 'Azoxistrobina (0.6 L/ha)', 'Benomilo (1 kg/ha)'], 'Evitar heridas grandes de poda. Sellar cortes con pasta cicatrizante. Buen drenaje.'),
('Duraznero', 'Cáncer bacterial', 'Pseudomonas syringae', 'Manchas oscuras hundidas en ramas con exudación. Brotes se secan en primavera. Hojas con manchas angulares negras.', 'Bacteria favorecida por lluvias y heladas primaverales. Temperaturas 10-20°C.', 'Alta', ARRAY['Cobre fijo (3 kg/ha) en caída de hojas y brotación', 'Sulfato de cobre (2 kg/ha)'], 'Poda en verano (no en lluvia). Desinfectar herramientas. Variedades resistentes.'),

-- Ciruelo
('Ciruelo', 'Viruela del ciruelo (Sharka)', 'Plum pox virus (PPV)', 'Manchas amarillas en anillos en hojas. Frutos deformes con manchas oscuras hundidas. Caída prematura de frutos.', 'Virus transmitido por pulgones. Enfermedad cuarentenaria en Chile. Sin cura.', 'Alta', ARRAY['NO HAY TRATAMIENTO QUÍMICO', 'Erradicar árboles infectados (obligatorio SAG)', 'Usar plantas certificadas libres de virus'], 'Comprar plantas certificadas. Control de pulgones vectores. Reportar al SAG.'),
('Ciruelo', 'Pudrición parda', 'Monilinia fructicola', 'Frutos con manchas marrones que se pudren rápidamente. Anillos de esporas beige en superficie. Frutos momificados.', 'Hongo favorecido por humedad y temperaturas 20-25°C. Entra por heridas de insectos o pájaros.', 'Alta', ARRAY['Fenhexamida (1.5 L/ha)', 'Ciprodinil + Fludioxonil (1.2 kg/ha)', 'Captan (3 kg/ha)'], 'Recoger frutos caídos y momificados. Poda de ventilación. Evitar heridas en frutos.'),

-- Arándano
('Arándano', 'Moho gris del arándano', 'Botrytis cinerea', 'Flores y frutos cubiertos de moho gris. Frutos se ponen blandos y acuosos. Ramillas con cancros.', 'Hongo que ataca en floración y fructificación. Favorecido por lluvias y alta humedad (>85%).', 'Alta', ARRAY['Fenhexamida (1.5 L/ha)', 'Ciprodinil + Fludioxonil (1.2 kg/ha)', 'Bacillus amyloliquefaciens (3 L/ha)'], 'Ventilar plantas con poda. Evitar exceso de nitrógeno. Recolectar frutos dañados.'),
('Arándano', 'Antracnosis', 'Colletotrichum acutatum', 'Manchas marrones-redondas en frutos maduros. Frutos se ablandan y cubren de esporas anaranjadas. Caída de frutos.', 'Hongo que sobrevive en restos vegetales. Favorecido por temperaturas 20-25°C y lluvias.', 'Media', ARRAY['Azoxistrobina (0.6 L/ha)', 'Captan (3 kg/ha)', 'Ziram (3 kg/ha)'], 'Poda de formación para ventilación. Mulch limpio bajo plantas. Recolección frecuente.'),

-- Nogal
('Nogal', 'Bacteriosis del nogal', 'Xanthomonas arboricola', 'Manchas negras en hojas y frutos. Nueces con manchas oscuras hundidas. Caída prematura de frutos.', 'Bacteria favorecida por lluvias primaverales y temperaturas 20-25°C. Entra por estomas y heridas.', 'Alta', ARRAY['Cobre fijo (3 kg/ha) en brotación', 'Sulfato de cobre (2 kg/ha)', 'Ziram (3 kg/ha)'], 'Poda de ventilación. Eliminar ramas bajas. Variedades tolerantes.'),
('Nogal', 'Polilla del nogal', 'Cydia pomonella', 'Gusanos dentro de las nueces. Perforan la cáscara blanda en formación. Nuez interior dañada y llena de excrementos.', 'Insecto que pasa el invierno como pupa en la corteza. Activo desde brotación hasta endurecimiento de cáscara.', 'Media', ARRAY['Clorpirifos (2 L/ha)', 'Fenoxicarb (1 L/ha)', 'Bacillus thuringiensis (1.5 kg/ha)'], 'Trampas de feromonas. Recolectar nueces caídas. Mantener tronco limpio de corteza muerta.'),

-- Naranjo / Limón
('Naranjo / Limón', 'Huanglongbing (HLB)', 'Candidatus Liberibacter spp.', 'Hojas con manchas amarillas asimétricas. Frutos pequeños, deformes, con sabor amargo. Caída de frutos. Árbol decae.', 'Bacteria transmitida por el psílido asiático Diaphorina citri. Enfermedad cuarentenaria SAG.', 'Alta', ARRAY['NO HAY CURA. Enfermedad cuarentenaria.', 'Control químico del psílido vector', 'Imidacloprid (0.5 L/ha) para vector'], 'Reportar al SAG inmediatamente. Control de psílidos. Usar plantas certificadas.'),
('Naranjo / Limón', 'Cancro de los cítricos', 'Xanthomonas citri', 'Lesiones corchosas elevadas en hojas, ramas y frutos. Bordes acuosos con halo amarillo. Caída de frutos y hojas.', 'Bacteria favorecida por temperaturas 25-30°C, viento y lluvia. Entra por heridas y estomas.', 'Alta', ARRAY['Cobre fijo (3 kg/ha) cada 14-21 días', 'Sulfato de cobre (2 kg/ha)', 'Estreptomicina agrícola (0.5 kg/ha)'], 'Barreras cortaviento. Desinfectar herramientas. Poda de ramas bajas.'),
('Naranjo / Limón', 'Minador de los cítricos', 'Phyllocnistis citrella', 'Galerías plateadas sinuosas en hojas jóvenes. Hojas se deforman y enrollan. Reduce fotosíntesis.', 'Insecto que ataca brotes nuevos. Favorecido por temperaturas 25-30°C. Múltiples generaciones al año.', 'Media', ARRAY['Abamectina (0.6 L/ha)', 'Imidacloprid (0.5 L/ha)', 'Aceite mineral parafínico (10 L/ha)'], 'Aceite de neem 5ml/L cada 15 días. Evitar fertilización nitrogenada excesiva.'),

-- Trigo
('Trigo', 'Roya amarilla del trigo', 'Puccinia striiformis', 'Pústulas amarillo-anaranjadas en hojas dispuestas en estrías. Hojas se secan prematuramente. Granos pequeños y arrugados.', 'Hongo que viaja largas distancias por viento. Favorecido por temperaturas 10-15°C y alta humedad.', 'Alta', ARRAY['Tebuconazol (1 L/ha)', 'Propiconazol (0.5 L/ha)', 'Azoxistrobina + Ciproconazol (0.8 L/ha)'], 'Variedades resistentes. Siembra temprana. Eliminar rastrojo. Rotación de cultivos.'),
('Trigo', 'Fusariosis de la espiga', 'Fusarium graminearum', 'Espigas con granos pequeños y decolorados. Granos con tono rosado-anaranjado. Produce micotoxinas dañinas.', 'Hongo favorecido por lluvias durante floración. Temperaturas 20-25°C. Restos de maíz infectados.', 'Alta', ARRAY['Tebuconazol (1 L/ha) en floración', 'Metconazol (0.6 L/ha)', 'Trifloxistrobina (0.3 L/ha)'], 'Rotación con no-cereales. Labranza profunda. Variedades tolerantes. Análisis de micotoxinas.'),

-- Planta ornamental (enfermedades polifágas comunes)
('Planta ornamental', 'Oídio generalizado', 'Erysiphaceae spp.', 'Polvo blanco en hojas, brotes y flores. Hojas se deforman y caen. Crecimiento detenido.', 'Hongos favorecidos por temperaturas 20-25°C, sombra y poca ventilación. Alta densidad de plantas.', 'Media', ARRAY['Azufre micronizado (2 kg/ha)', 'Penconazol (0.3 L/ha)', 'Miclobutanil (0.3 L/ha)'], 'Azufre en polvo espolvoreado cada 7 días. Ventilar el invernadero/sombreadero.'),
('Planta ornamental', 'Mosquita blanca', 'Trialeurodes vaporariorum', 'Pequeños insectos blancos en envés. Hojas pegajosas con fumagina negra. Debilidad y caída de hojas.', 'Insecto polífago que ataca cientos de especies. Favorecido por temperaturas cálidas.', 'Media', ARRAY['Imidacloprid (0.5 L/ha)', 'Buprofezin (1 L/ha)', 'Beauveria bassiana (2 kg/ha)'], 'Trampas pegajosas amarillas. Jabón potásico 20ml/L. Depredador: Encarsia formosa.'),
('Planta ornamental', 'Pudrición de raíz', 'Pythium spp.', 'Marchitez repentina. Raíces negras y blandas. Tallo base oscuro. Plantas se caen y mueren rápido.', 'Hongo del suelo favorecido por exceso de riego, mal drenaje y sustrato contaminado.', 'Alta', ARRAY['Fosetil-Al (3 L/ha en drench)', 'Metalaxil-M (1 L/ha en drench)', 'No hay cura avanzada'], 'Mejorar drenaje. Regar solo cuando sea necesario. Usar sustrato esterilizado.'),

-- Otro (polífagas — aplican a múltiples cultivos)
('Otro', 'Pulgones generalizados', 'Aphididae spp.', 'Colonias de pequeños insectos verdes, negros o amarillos en brotes y envés. Hojas deformadas y pegajosas.', 'Insectos polífagos que atacan casi cualquier cultivo. Favorecidos por temperaturas 20-25°C.', 'Media', ARRAY['Imidacloprid (0.5 L/ha)', 'Pirimicarb (0.5 kg/ha)', 'Azadiractina (1 L/ha)'], 'Jabón potásico 15ml/L cada 3 días. Depredadores: chinitas. Riego fuerte para desprender.'),
('Otro', 'Trips generalizados', 'Thysanoptera spp.', 'Raspado plateado en hojas. Puntos negros (excrementos). Hojas deformes y brotes dañados. Transmiten virus.', 'Insectos polífagos muy pequeños. Favorecidos por clima cálido-seco. Difíciles de controlar.', 'Media', ARRAY['Spinosad (0.5 L/ha)', 'Abamectina (0.6 L/ha)', 'Beauveria bassiana (2 kg/ha)'], 'Trampas adhesivas azules. Aceite de neem 5ml/L. Mantener humedad ambiental.'),
('Otro', 'Arañita roja', 'Tetranychus urticae', 'Punteado amarillo en hojas. Telarañas finas en envés. Hojas se secan y caen. Infestación rápida en climas secos.', 'Ácaro polífago favorecido por clima cálido-seco (>25°C, <60% HR). Se reproduce cada 5-7 días.', 'Media', ARRAY['Abamectina (0.6 L/ha)', 'Aceite mineral parafínico (10 L/ha)', 'Fenpiroximato (0.5 L/ha)'], 'Aceite de neem 5ml/L cada 7 días. Mantener humedad >70%. Depredador: Phytoseiulus persimilis.'),
('Otro', 'Nemátodos del suelo', 'Meloidogyne spp.', 'Amarillamiento general. Raíces con nódulos o agallas. Plantas raquíticas. Marchitez en horas de calor.', 'Nemátodos polífagos que viven en raíces. Favorecidos por suelos arenosos y monocultivo.', 'Media', ARRAY['Oxamilo (5 L/ha) en drench', 'Fenamifos (30 L/ha) — uso profesional', 'Rotación de cultivos obligatoria'], 'Solarización del suelo (plástico transparente 4-6 semanas). Abono orgánico. Variedades resistentes.')
ON CONFLICT DO NOTHING;
